bboard/urls.py
from django.urls import path

from .views import index, by_rubric, rubrics ,BbCreateView, BbDetailView, BbEditView, BbDeleteView

app_name = 'bboard'

urlpatterns = [
    path('edit/<int:pk>/', BbEditView.as_view(), name='edit'),
    path('edit/rubrics/', rubrics, name='edit_rubrics'),
    path('add/', BbCreateView.as_view(), name='add'),
    path('<int:rubric_id>/', by_rubric, name='by_rubric'),
    path('', index, name='index'),
    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('detail/<int:pk>/delete/', BbDeleteView.as_view(), name='delete_bb')
    
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('', include('bboard.urls')),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/login/', LoginView.as_view(template_name = 'registration/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page=None), name='logout'),
    path('accounts/password_change/', PasswordChangeView.as_view(), name='password_change'),
    # path('accounts/profile/',  ,name='profile')
]

users/urls.py
from django.urls import path
from users.views import SignUpView


urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

bboard/models.py
from django.db import models
# Create your models here.


class Bb(models.Model):
    BUY = 'b'
    SELL = 's'
    CHANGE = 'c'
    KINDS = (
        (BUY, 'Куплю'), (SELL, 'Продам'), (CHANGE, 'Обменяю'),
    )
    title = models.CharField(max_length=50, verbose_name='Товар')
    content = models.TextField(null=True, blank=True, verbose_name='Описание')
    kind = models.CharField(max_length=1, choices=KINDS, default='s', verbose_name='Тип')
    price = models.FloatField(null=True, blank=True, verbose_name='Цена')
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')
    rubric = models.ForeignKey('Rubric', null=True, on_delete=models.PROTECT, verbose_name='Рубрика')

    class Meta:
        verbose_name_plural = 'Объявления'
        verbose_name = 'Объявление'
        ordering = ['-published']

    # def title_and_price(self): 
    #     if self.price:
    #         return '%s (%.2f)' % (self.title, self.price) 
    #     else:
    #         return self.title

class Rubric(models.Model):
    name = models.CharField(max_length=15, db_index=True, verbose_name='Название')
    order = models.SmallIntegerField(default=1, db_index=True)

    def __str__(self):
        return self.name
    
    # def get_absolute_url():
    #     return "/bboard/%s/" % self.pk

    class Meta:
        verbose_name_plural = 'Рубрики'
        verbose_name = 'Рубрика'
        ordering = ['order' ,'name']

bboard/forms.py
from django import forms
from .models import Bb, Rubric
from django.core.exceptions import ValidationError


class BbForm(forms.ModelForm):
    title = forms.CharField(label='Название товара')
    content = forms.CharField(label='Описание', widget=forms.widgets.Textarea())
    price = forms.DecimalField(label='Цена', decimal_places=2)
    rubric = forms.ModelChoiceField(queryset=Rubric.objects.all(), 
                                    label='Рубрика', 
                                    help_text='Не забудьте выбрать рубрику!')

    class Meta:
        model = Bb
        fields = ('title', 'content', 'price', 'kind', 'rubric')
    
    def clean(self):
        super().clean()
        errors = {}
        if not self.cleaned_data['content']:
            errors['content'] = ValidationError('Укажите описание товара!')
        if self.cleaned_data['price'] < 0:
            errors['price'] = ValidationError('Укажите неотрицательное значени цены!')
        if errors:
            raise ValidationError(errors)
            

bboard/views.py
# from django.template import loader
from django.forms import modelformset_factory
from django.forms.formsets import ORDERING_FIELD_NAME
from django.shortcuts import render, redirect
# from django.http import JsonResponse, HttpResponseRedirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.dates import ArchiveIndexView
from django.urls import reverse_lazy, reverse
from django.core import serializers
from django.core.paginator import Paginator
from django.contrib.auth.decorators import user_passes_test


from .forms import BbForm
from .models import Bb, Rubric


def index(request):

    rubrics = Rubric.objects.all() 
    bbs = Bb.objects.all() 
    paginator = Paginator(bbs, 2) 
    if 'page' in request.GET:
        page_num = request.GET['page'] 
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'rubrics': rubrics, 'page': page, 'bbs': page.object_list} 
    return render(request, 'bboard/index.html', context)

    # template = loader.get_template('bboard/index.html')
    # bbs = Bb.objects.order_by('-published')
    # context = {'bbs': bbs}
    # return HttpResponse(template.render(context, request))


# def index(request):
#     s = 'Список объявлений\r\n\r\n\r\n'
#     for bb in Bb.objects.order_by('-published'):
#         s += bb.title + '\r\n' + bb.content + '\r\n\r\n'
#     return HttpResponse(s, content_type='text/plain; charset=utf-8')


def by_rubric(request, rubric_id):
    bbs = Bb.objects.filter(rubric=rubric_id)
    rubrics = Rubric.objects.all()
    current_rubric = Rubric.objects.get(pk=rubric_id)
    # rubric_serialized = serializers.serialize("python", rubrics.values(), ensure_ascii=False)
    # return JsonResponse(list(rubrics), safe=False)
    # return JsonResponse(rubric_serialized, safe=False)

    # json_object = {'key': "value"}
    # return JsonResponse(json_object)

    context = {'bbs': bbs, 'rubrics': rubrics, 'current_rubric': current_rubric}
    return render(request, 'bboard/by_rubric.html', context)


@user_passes_test (lambda user: user.is_staff)
def rubrics(request):
    RubricFormSet = modelformset_factory(Rubric, fields=('name',),
                                        can_order=True, can_delete=True)
    if request.method == 'POST':
        formset = RubricFormSet(request.POST) 
        if formset.is_valid():
            for form in formset:
                if form.cleaned_data:
                    rubric = form.save(commit=False)
                    rubric.order = form.cleaned_data[ORDERING_FIELD_NAME] 
                    rubric.save()
            return redirect('bboard:index')
    else:
        formset = RubricFormSet()
        context = {'formset': formset}
        return render(request, 'bboard/rubrics.html', context)


class BbCreateView(CreateView):
    template_name = 'bboard/create.html/'
    form_class = BbForm
    success_url = reverse_lazy('bboard:index')

# чтобы рубрики отображались на странице ввода
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context


class BbDetailView(DetailView):
    model = Bb
    # template_name = 'bboard/bb_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context


class BbEditView(UpdateView): 
    model = Bb
    form_class = BbForm 
    success_url = reverse_lazy('bboard:index')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs) 
        context['rubrics'] = Rubric.objects.all()
        return context


class BbDeleteView(DeleteView): 
    model = Bb
    success_url = '/'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs) 
        context['rubrics'] = Rubric.objects.all ()
        return context


class BbIndexView(ArchiveIndexView): 
    model = Bb
    date_field = 'published'
    date_list_period = 'day'
    template_name = 'bboard/index.html' 
    context_object_name = 'bbs' 
    allow_empty = True

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs) 
        context['rubrics'] = Rubric.objects.all()
        return context

templates/bboard/bb_confirm_delete.html
{% extends "layout/basic.html" %}

{% block title %}Удаление объявления{% endblock %}

{% block content %}
<h2>Удаление объявления</h2> 
<p>Рубрика: {{ bb.rubric.name }}</р> 
<p>Товар: {{ bb.title }}</р>
<p>{{ bb.content }}</p>
<p>Цена: {{ bb.price }}</р>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
</form>
{% endblock %}

templates/bboard/bb_detail.html
{% extends "layout/basic.html" %}

{% block title %}{{ bb.title }}{% endblock %}

{% block content %}
<p>Рубрика: {{ bb.rubric.name }}</p>
<h2>{{ bb.title }}</h2>
<p>Описание: {{ bb.content }}</p>
<p>Цена: {{ bb.price }}</p>
<form action="">

</form>
{% endblock %}

templates/bboard/bb_form.html
{% extends "layout/basic.html" %}

{% block title %}Редактирование объявления{% endblock %}

{% block content %}
<h2>Редактирование объявления</h2>

<form method="post">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %} 
        {{ hidden }}
    {% endfor %}
    {% if form.non_field_errors %}
    <ul>
        {% for error in form.non_field_errors %}
        <li><em>{{ error|escape }}</em></li> 
        {% endfor %}
    </ul>
    {% endif %}
    {% for field in form.visible_fields %} 
        {% if field.errors %}
        <ul>
            {% for error in field.errors %}
            <li><em>{{ error|escape }}</em></li> 
            {% endfor %}
        </ul>
        {% endif %}
        <p>{{ field.label_tag }}<br>{{ field }}<br> 
        {{ field.help_text }}</p>
    {% endfor %}
    <!-- {{ form.as_p }} -->
    <p><input type="submit" value="Сохранить"></p>
</form>
{% endblock %}

templates/bboard/by_rubric.html
{% extends "layout/basic.html" %}

{% block title %}{{ current_rubric.name }}{% endblock %}

{% block content %}
<h2>Рубрика: {{ current_rubric.name }}</h2>

{% for bb in bbs %}
<div>
    <h2><a href="{% url 'bboard:detail' pk=bb.pk %}">{{ bb.title }}</a></h2>
    <p>{{ bb.content }}</p>
    <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
</div>
{% endfor %}
{% endblock %}

templates/bboard/create.html
{% extends "layout/basic.html" %}

{% block title %}Добавление объявления{% endblock %}

{% block content %}
<h2>Добавление объявления</h2>

<!-- создать форму: кнопка "Добавить", цифровой жетон, и выводит эл. управления формой  -->
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить">
</form>
{% endblock %}

templates/bboard/index.html
{% extends "layout/basic.html" %}

{% block content %}
{% for bb in bbs %}
<div>
    <h2><a href="{% url 'bboard:detail' pk=bb.pk %}">{{ bb.title }}</a></h2>
    <!-- <h2>{{ bb.title_and_price }}</h2> -->
    <p>{{ bb.content }}</p>
    <p>{{ bb.get_kind_display }}</p>
    <p><a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">{{ bb.rubric.name }}</a></p>
    <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
</div>
{% endfor %}
<div>
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">&lt;</a> 
    &nbsp; &nbsp; | &nbsp; &nbsp;
    {% endif %}
    Часть №{{ page.number }} из {{ page.paginator.num_pages }} 
    {% if page.has_next %}
    &nbsp; &nbsp; | &nbsp; &nbsp;
    <a href="?page={{ page.next_page_number }}">&gt;</a>
    {% endif %} 
</div>
{% endblock %}

templates/bboard/rubrics.html
<form method="post"> 
    {% csrf_token %}
    {{ formset.management_fonn }}
    {% if formset.non_form_errors %}
    <ul>
        {% for error in formset.non_form_errors %}
        <li><em>{{ error|escape }}</em></li> 
        {% endfor %}
    </ul>
    {% endif %}
    {% for form in formset %}
        {% for hidden in form.hidden_fields %} 
            {{ hidden }}
        {% endfor %}
        {% if form.non_field_errors %}
        <ul>
            {% for error in form.non_field_errors %}
            <li><em>{{ error|escape }}</em></li> 
            {% endfor %}
        </ul>
        {% endif %}
        {% for field in form.visible_fields %}
            {% if field.errors %} 
            <ul>
                {% for error in field.errors %} 
                <li><em>{{ error|escape }}</em></li>
                {% endfor %} 
            </ul>
            {% endif %}
            <p>{{ field.label_tag }}<br>{{ field }}<br>
            {{ field.help_text }}</p> 
        {% endfor %}
    {% endfor %}
    <input type="submit" value="Coxpaнить">
</form>