bboard/urls.py
from django.urls import path

from .views import index, by_rubric, rubrics ,BbCreateView, BbDetailView, BbEditView, BbDeleteView

app_name = 'bboard'

urlpatterns = [
    path('edit/<int:pk>/', BbEditView.as_view(), name='edit'),
    path('edit/rubrics/', rubrics, name='edit_rubrics'),
    path('add/', BbCreateView.as_view(), name='add'),
    path('<int:rubric_id>/', by_rubric, name='by_rubric'),
    path('', index, name='index'),
    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('detail/<int:pk>/delete/', BbDeleteView.as_view(), name='delete_bb')
    
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('', include('bboard.urls')),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/login/', LoginView.as_view(template_name = 'registration/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page=None), name='logout'),
    path('accounts/password_change/', PasswordChangeView.as_view(), name='password_change'),
    # path('accounts/profile/',  ,name='profile')
]

users/urls.py
from django.urls import path
from users.views import SignUpView


urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

templates/layout/basic.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Главная{% endblock %} :: Доска объявлений</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bboard/style.css' %}">
</head>
<body>
    <header>
        <h1>Объявления</h1>
    </header>
    <div class="topnav">
        <a href="{% url 'bboard:index' %}">Главная</a>
        <div class="topnav-right">
            {% if user.is_anonymous %}
                <a href="{% url 'login' %}">Вход</a>
                <a href="{% url 'signup' %}">Регистрация</a>
            {% else %}
                <a href="{% url 'bboard:index' %}">Личный кабинет</a>   
            {% endif %}
        </div>
    </div>
    <nav>
        {% if user.is_authenticated %}
            <a href="{% url 'bboard:add' %}">Добавить</a>
        {% endif %}
        {% for rubric in rubrics %}
            <a href="{% url 'bboard:by_rubric' rubric.pk %}">{{ rubric.name }}</a>
        {% endfor %}
    </nav>
    <section>
        {% block content %}
        {% endblock %}
    </section>
</body>
</html>